### ISSUE TITLE
Can you give an example on parsing xml

### ISSUE THREAD

**Issue by Rameen15** [reliqarts/laravel-scavenger#5]
i want to use this package to scrape xml data .....but i want to use the config file to define my tags and parameter just like you did in example :
     'bing' => [
            'example' => true,
            'serp' => true,
            'model' => 'App\\BingResult',
            'source' => 'https://www.bing.com',
            'search' => [
                'keywords' => ['dog'],
                'form' => [
                    'selector' => 'form#sb_form',
                    'keyword_input_name' => 'q',
                ],
            ],
            'pages' => 3,
            'pager' => [
                'selector' => '.sb_pagN',
            ],
            'markup' => [
                '__result' => '.b_algo',
                'title' => 'h2 a',
                'description' => '.b_caption p',
                'link' => '__link',
                'position' => '__position',
            ],

example url from where i want to fetch my data [https://www.geo.tv/rss/1/0](https://www.geo.tv/rss/1/0)

`` i want to fetch all the adat in item tags => 
 <channel>
<title>GEO TV - Entertainment</title>
<atom:link href="https://www.geo.tv/rss/1/0" rel="self" type="application/rss+xml"/>
<link>https://www.geo.tv/</link>
<description>GeoTV, Geo News, Latest-News, Breaking News, Pakistan, Live Videos</description>
<lastBuildDate>Mon, 25 Jul 2022 15:59:12 +0500</lastBuildDate>
<language>en-US</language>
<item>
<title>
<![CDATA[ Kate Hudson gives sneak peek of fun day out with her daughter: Photo ]]>
</title>
<link>
<![CDATA[ https://www.geo.tv/latest/429659-kate-hudson-gives-sneak-peek-of-fun-day-out-with-her-daughter-photo ]]>
</link>
<pubDate>
<![CDATA[ Mon, 25 Jul 2022 16:00:48 +0000 ]]>
</pubDate>
<guid>
<![CDATA[ https://www.geo.tv/latest/429659-kate-hudson-gives-sneak-peek-of-fun-day-out-with-her-daughter-photo ]]>
</guid>
<description>
<![CDATA[ <img src="https://www.geo.tv/assets/uploads/updates/2022-07-25/l_429659_035906_updates.jpg"/> ]]>
<![CDATA[ Kate Hudson posts adorable photo with her daughter on social media ]]>
</description>
</item>
<item>
<title>
<![CDATA[ Prince Harry not afraid to â€˜say what he really feelsâ€™ in memoir ]]>
</title>
<link>
<![CDATA[ https://www.geo.tv/latest/429648-prince-harry-not-afraid-to-say-what-he-really-feels-in-memoir ]]>
</link>
<pubDate>
<![CDATA[ Mon, 25 Jul 2022 15:56:00 +0000 ]]>
</pubDate>
<guid>
<![CDATA[ https://www.geo.tv/latest/429648-prince-harry-not-afraid-to-say-what-he-really-feels-in-memoir ]]>
</guid>
<description>
<![CDATA[ <img src="https://www.geo.tv/assets/uploads/updates/2022-07-25/l_429648_035642_updates.jpg"/> ]]>
<![CDATA[ Prince Harry is said to not be afraid of speaking his mind in his upcoming memoir, as per a royal expert ]]>
</description>
</item>``

**Comment by reliq** [comment]
Hi @Rameen15, unfortunately this package does not support XML and there is no bandwidth to implement this feature at this time. Please feel free to make a PR with this enhancement.
